version: '3.8'

services:
  
  ### Slice 1: ue111 ~ ue119 
  ### Slice 2: ue121 ~ ue129
  ## naming Convesion ue{xy}: x here is slice number, y here ue

  ueransim-ue11:
    container_name: ue11
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/uecfg.yaml
    volumes:
      - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice1/ue11cfg.yaml:/ueransim/config/uecfg.yaml
      - ./data/ue:/ueransim/data
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue11.free5gc.org

  ueransim-ue12:
    container_name: ue12
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/uecfg.yaml
    volumes:
      - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice1/ue12cfg.yaml:/ueransim/config/uecfg.yaml
      - ./data/ue:/ueransim/data
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue12.free5gc.org

  # ueransim-ue13:
  #   container_name: ue13
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice1/ue13cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue13.free5gc.org

  # ueransim-ue14:
  #   container_name: ue14
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice1/ue14cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue14.free5gc.org

  #slice2 start here
  ueransim-ue21:
    container_name: ue21
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/uecfg.yaml
    volumes:
      - ./config/slice2/gnb21cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice2/ue21cfg.yaml:/ueransim/config/uecfg.yaml
      - ./data/ue:/ueransim/data
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue21.free5gc.org

  ueransim-ue22:
    container_name: ue22
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/uecfg.yaml
    volumes:
      - ./config/slice2/gnb21cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice2/ue22cfg.yaml:/ueransim/config/uecfg.yaml
      - ./data/ue:/ueransim/data
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue22.free5gc.org

  # ueransim-ue23:
  #   container_name: ue23
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice2/gnb21cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice2/ue23cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue23.free5gc.org

  # ueransim-ue24:
  #   container_name: ue24
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice2/gnb21cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice2/ue24cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue24.free5gc.org  

  # #slice3 start here
  # ueransim-ue31:
  #   container_name: ue31
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice3/gnb31cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice3/ue31cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue31.free5gc.org
  
  # ueransim-ue32:
  #   container_name: ue32
  #   image: free5gc/ueransim:latest
  #   command: ./nr-ue -c ./config/uecfg.yaml
  #   volumes:
  #     - ./config/slice3/gnb31cfg.yaml:/ueransim/config/gnbcfg.yaml
  #     - ./config/slice3/ue32cfg.yaml:/ueransim/config/uecfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - "/dev/net/tun"
  #   networks:
  #     privnet:
  #       aliases:
  #         - ue32.free5gc.org


  
networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
