wg_private_key: "{{ lookup('file', 'files/controlplane_1') }}"
wg_ip: "10.100.100.1/24"

wg_peers:
  - public_key: "{{ lookup('file', 'files/dataplane_1.pub') }}"
    endpoint: "{{ hostvars['dataplane_1']['ansible_host'] }}:{{ wg_port }}"
    allowed_ips: "10.100.100.2/32"
