#version: '3.8'

services:
  free5gc-upf:
    container_name: upf
    image: free5gc/upf:v3.4.1
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/slice1/upf1cfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
      - ./data/upf:/data
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.200.100.150
        aliases:
          - upf.free5gc.org
    extra_hosts:
      - "smf.free5gc.org:10.200.100.20"



  ueransim-gnb11:
    container_name: ueransim-gnb11
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slicle1/ue11cfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb.free5gc.org
    extra_hosts:
      - "smf.free5gc.org:10.200.100.20"
      - "amf.free5gc.org:10.200.100.15"
   
  ueransim-ue11:
    container_name: ue11
    image: free5gc/ueransim:latest
    command: ./nr-ue -c ./config/uecfg.yaml
    volumes:
      - ./config/slice1/gnb11cfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/slice1/ue12cfg.yaml:/ueransim/config/uecfg.yaml
      - ./data/ue:/data
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue11.free5gc.org

networks:
  privnet:  # 5G functions are connected with this
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.100.128/25
          gateway: 10.200.100.129
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

  
volumes:
  dbdata:



