#version: '3.8'

services:
  #Server
  server_11:
    container_name: server_11
    #image: tleemcjr/metasploitable2
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.11
        aliases:
          - server11
  #Server
  server_12:
    container_name: server_12
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.12
        aliases:
          - server12

  #Server for slice 2
  server_21:
    container_name: server_21
    #image: tleemcjr/metasploitable2
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.21
        aliases:
          - server21
  #Server
  server_22:
    container_name: server_22
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.22
        aliases:
          - server22
  #Server (for slice3)
  server_31:
    container_name: server_31
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.31
        aliases:
          - server31

  server_32:
    container_name: server_32
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      publicnet:
        ipv4_address: 10.200.200.32
        aliases:
          - server32

  # Server to be connected to mlids (upf -> mlids -> server)
  server_mlids_21:
    container_name: server_mlids_21
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      after_mlids:
        ipv4_address: 10.50.50.21
        aliases:
          - server_mlids_21

  server_mlids_22:
    container_name: server_mlids_22
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      after_mlids:
        ipv4_address: 10.50.50.22
        aliases:
          - server_mlids_22

  server_mlids_12:
    container_name: server_mlids_12
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      after_mlids:
        ipv4_address: 10.50.50.12
        aliases:
          - server_mlids_12

  server_mlids_13:
    container_name: server_mlids_13
    image: sohag07hasan/ubuntu-uofr:22.04
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      after_mlids:
        ipv4_address: 10.50.50.13
        aliases:
          - server_mlids_13


  # vulnerable webserver 
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    # Change `always` to `build` to build from local source
    pull_policy: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./DVWA/dvwa:/DVWA/dvwa
      - ./config:/config
      - ./data:/data
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      publicnet:
       ipv4_address: 10.200.200.13
       aliases:
        - dvwa
      after_mlids:
        ipv4_address: 10.50.50.50
        aliases:
          - dvwa
    ports:
      - 127.0.0.1:4280:443
    restart: unless-stopped
  # Data Base for the vulnerable webserver
  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - ./DVWA/dvwa:/var/lib/mysql
    networks:
      publicnet:
        ipv4_address: 10.200.200.14
        aliases:
          - dvwadb
    restart: unless-stopped 



    # Vulnerable webserver
  dvwa2:
    image: sohag07hasan/dvwa:v1  # Using your custom image
    cap_add:
      - NET_ADMIN
    volumes:
      - ./DVWA2/dvwa:/DVWA/dvwa
      - ./config:/config
      - ./data:/data
    environment:
      - DB_SERVER=db2
    depends_on:
      - db2
    networks:
      publicnet:
        ipv4_address: 10.200.200.15
        aliases:
          - dvwa2
      after_mlids:
        ipv4_address: 10.50.50.51
        aliases:
          - dvwa2
    ports:
      - 127.0.0.1:4281:443
    restart: unless-stopped

  # Database for the vulnerable webserver
  db2:
    image: sohag07hasan/dvwadb:v1  # Using your custom database image
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - ./DVWA2/dvwa:/var/lib/mysql
    networks:
      publicnet:
        ipv4_address: 10.200.200.116
        aliases:
          - dvwadb2
    restart: unless-stopped

networks:
  publicnet:  # Name of the new network
    external: true
    name: free5gc-compose-uofr_publicnet

  after_mlids:  # Name of the new network
    external: true
    name: free5gc-compose-uofr_after_mlids
