- name: Test Ansible Setup
  hosts: builder
  gather_facts: false
  become: yes
  tasks:
    - name: Print hostname
      command: hostname
      register: result
    
    - name: Show hostname
      debug:
        msg: "{{ result.stdout }}"