global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

rule_files:
  - /etc/prometheus/recording_rules.yml  # Add recording rules if applicable

scrape_configs:
- job_name: cadvisor
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets:
    - cadvisor:8080
  relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'cadv'
  metric_relabel_configs:
    - source_labels: [__name__] # Operate on metric names
      regex: "container_network_.*"  # Only collect network-related metrics
      action: keep
    - source_labels: [name] # Operate on the container name label
      regex: "^(ue.*|upf.*|server.*|mlids.*)$" # Specify container names to match
      #regex: "ue22|ue21"
      action: keep
    # - action: drop # Drop all other metrics

# Commented out nodeexporter to reduce load
# - job_name: nodeexporter
#   honor_timestamps: true
#   scheme: http
#   static_configs:
#   - targets:
#     - nodeexporter:9100
#   relabel_configs:
#     - source_labels: [__address__]
#       regex: '.*'
#       target_label: instance
#       replacement: 'node'
