groups:
  - name: cadvisor_network
    rules:
      - record: instance:container_network_receive_bytes_per_second
        expr: irate(container_network_receive_bytes_total[2s])
      - record: instance:container_network_transmit_bytes_per_second
        expr: irate(container_network_transmit_bytes_total[2s])
