- name: Test Connectivity (Ping Test)
  ansible.builtin.ping:

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install essential tools
  apt:
    name:
      - docker.io
      - git
      - wireguard
      - gcc
      - make
      - tree
      - dos2unix
    state: present

- name: Install Docker Compose v2 plugin
  become: true
  shell: |
    DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
    mkdir -p /usr/lib/docker/cli-plugins
    curl -SL https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/lib/docker/cli-plugins/docker-compose
  args:
    creates: /usr/lib/docker/cli-plugins/docker-compose


- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  
