#Check connectivity
- import_playbook: playbooks/check.yaml

#Setup Wiregulard among the EC2 instances
- import_playbook: playbooks/wireguard.yaml

#Setup Control Plane
- import_playbook: playbooks/control.yaml

#Setup Data Plane
- import_playbook: playbooks/data.yaml