//Control Node
root@ip-10-10-1-8:~# cat /etc/wireguard/wg0.conf
[Interface]
Address = 10.100.100.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enX0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enX0 -j MASQUERADE
ListenPort = 51820
PrivateKey = eFUC23ZcntqGKUXaRbleh+/EYE1+/5X6xFB1NpxdRlc=

[Peer]
PublicKey = ie8Laj+eMSR1npOh1NyVS0g5JB3yQwMJ9qlOwCpm4GA=
AllowedIPs = 10.100.100.2/32, 10.200.100.128/25
Endpoint = 3.101.125.69:51820
PersistentKeepalive = 25
root@ip-10-10-1-8:~#


ubuntu@ip-10-10-1-8:~/5GTB$ ip route
default via 10.10.1.1 dev enX0 proto dhcp src 10.10.1.8 metric 100
10.10.0.2 via 10.10.1.1 dev enX0 proto dhcp src 10.10.1.8 metric 100
10.10.1.0/24 dev enX0 proto kernel scope link src 10.10.1.8 metric 100
10.10.1.1 dev enX0 proto dhcp scope link src 10.10.1.8 metric 100
10.100.100.0/24 dev wg0 proto kernel scope link src 10.100.100.1
10.200.100.0/25 dev br-free5gc proto kernel scope link src 10.200.100.1
10.200.100.128/25 dev wg0 scope link
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
ubuntu@ip-10-10-1-8:~/5GTB$



-------------------------------------------------------------------------------------------------
Data Node:

root@ip-10-20-1-253:~# cat /etc/wireguard/wg0.conf
[Interface]
Address = 10.100.100.2/24
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enX0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enX0 -j MASQUERADE
ListenPort = 51820
PrivateKey = 4MmpHYGzDmd4uJT4YK6i7kdXmCFj2AJg80trPl3+um4=

[Peer]
PublicKey = B+Ge3hSHKV3DeFbaB7Jqp+KIyEWcx3lAoKV4KBY5sng=
AllowedIPs = 10.100.100.1/32, 10.200.100.0/25
Endpoint = 54.221.63.223:51820
PersistentKeepalive = 25
root@ip-10-20-1-253:~#



ubuntu@ip-10-20-1-253:~/5GTB/5g-cnf/free5gc-compose-UofR$ ip route
default via 10.20.1.1 dev enX0 proto dhcp src 10.20.1.253 metric 100
10.20.0.2 via 10.20.1.1 dev enX0 proto dhcp src 10.20.1.253 metric 100
10.20.1.0/24 dev enX0 proto kernel scope link src 10.20.1.253 metric 100
10.20.1.1 dev enX0 proto dhcp scope link src 10.20.1.253 metric 100
10.100.100.0/24 dev wg0 proto kernel scope link src 10.100.100.2
10.200.100.0/25 dev wg0 scope link
10.200.100.128/25 dev br-free5gc proto kernel scope link src 10.200.100.129
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown




